# Generated by Django 5.0.1 on 2024-02-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продукта'},
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.FloatField()),
                ('product_des', models.TextField()),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Наши продукты',
                'verbose_name_plural': 'Наши продукты',
            },
        ),
    ]
