# Generated by Django 5.0.1 on 2024-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
